name: submeowsions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  flutter_riverpod:
  freezed_annotation:
  json_annotation:
  go_router: ^17.0.1
  uuid:
  hooks_riverpod:
  flutter_hooks:
  window_manager:
  cupertino_icons:
  riverpod_annotation: ^4.0.0
  intl: ^0.20.2
  custom_mouse_cursor: ^1.1.3
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  path: ^1.9.1
  path_provider: ^2.1.5
  drift_db_viewer:
  flutter_typeahead: ^5.2.0
  conversion:
  material_symbols_icons:
  shared_preferences: 
  circular_menu:
  pie_menu: ^3.3.3
  file_picker: ^10.3.8
  flutter_colorpicker:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator:
  custom_lint:
  build_runner:
  riverpod_lint:
  freezed:
  json_serializable:
  drift_dev: ^2.30.0

flutter:
  uses-material-design: true
  assets:
    - assets/